repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - -i
          - -r
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-tidy-imports
          - flake8-quotes
